import fs from 'node:fs/promises';
import { SpreadsheetFile, Workbook } from '@oai/artifact-tool';

const baseDir='C:/Users/Wesley/Documents/Dev Alc/Projetos/bonificacao-dispatcher';
const outDir=`${baseDir}/outputs/thread-01`;
const summary=JSON.parse(await fs.readFile(`${outDir}/ff_summary.json`,'utf8'));
const ffRoutes=JSON.parse(await fs.readFile(`${outDir}/ff_routes.json`,'utf8'));
const wb=Workbook.create();
const dash=wb.worksheets.add('Dashboard FF');
const base=wb.worksheets.add('Resumo por Base');
const routes=wb.worksheets.add('Rotas FF');
const rules=wb.worksheets.add('Regras');
const dict=wb.worksheets.add('Dicionário');
const reserve=wb.worksheets.add('Cadastro Reserva FF');
for(const s of [dash,base,routes,rules,dict,reserve]) s.showGridLines=false;
const navy='#24232F', purple='#7368F0', pale='#F2F0FF', blue='#62A4E9', green='#44C18D', orange='#EF9C62', red='#F08080', gray='#F4F4F6', text='#252631', muted='#7E7F8B';
const setTitle=(s,range,title,subtitle)=>{s.getRange(range).merge();s.getRange(range.split(':')[0]).values=[[title]];s.getRange(range).format={fill:navy,font:{bold:true,color:'#FFFFFF',size:18},verticalAlignment:'Center'};s.getRange(range).format.rowHeight=34; if(subtitle){const row=Number(range.match(/\d+/)[0])+1;const end=range.split(':')[1].replace(/\d+/,'')+row;s.getRange(`${range.split(':')[0].replace(/\d+/,'')}${row}:${end}`).merge();s.getRange(`${range.split(':')[0].replace(/\d+/,'')}${row}`).values=[[subtitle]];s.getRange(`${range.split(':')[0].replace(/\d+/,'')}${row}`).format={font:{color:muted,italic:true,size:10}};}};
const hdr=(s,range)=>{s.getRange(range).format={fill:'#EDECF7',font:{bold:true,color:navy,size:10},borders:{bottom:{style:'thin',color:'#C9C8D7'}}};};
const box=(s,range,fill='#FFFFFF')=>{s.getRange(range).format={fill,borders:{preset:'outside',style:'thin',color:'#E8E8EE'}};};

setTitle(dash,'A1:H1','BÔNUS CONTROL · FROTA FIXA','Fonte: Rotas 1 a 31 Julho DDS preenchida.xlsx · aba Geral · leitura calculável do mês');
dash.getRange('A4:H4').values=[['JULHO 2026','Bases analisadas','Rotas FF totais','Rotas FF elegíveis','DS médio FF','Bônus projetado*','Ambulâncias','Status']];hdr(dash,'A4:H4');
dash.getRange('A5').values=[['Fechamento mensal']];dash.getRange('B5:H5').formulas=[["=COUNTA('Resumo por Base'!$A$4:$A$47)","=SUM('Resumo por Base'!$B$4:$B$47)","=SUM('Resumo por Base'!$C$4:$C$47)","=SUM('Rotas FF'!$D$4:$D$797)/COUNT('Rotas FF'!$D$4:$D$797)", "=SUM('Resumo por Base'!$G$4:$G$47)","=SUM('Resumo por Base'!$D$4:$D$47)","=IF(F5=0,\"Sem projeção oficial\",\"Projeção por participação FF\")"]];box(dash,'A5:H5');dash.getRange('A5:H5').format.rowHeight=28;
dash.getRange('E5').format.numberFormat='0.0%';dash.getRange('F5').format.numberFormat='R$ #,##0';
dash.getRange('A8:H8').merge();dash.getRange('A8').values=[['RANKING · PARTICIPAÇÃO DE ROTAS FF POR BASE']];dash.getRange('A8').format={font:{bold:true,color:navy,size:12}};
dash.getRange('A9:D9').values=[['#','Base','Participação FF*','DS médio FF']];hdr(dash,'A9:D9');
for(let i=0;i<10;i++){const row=10+i;dash.getRange(`A${row}:D${row}`).formulas=[[`=${i+1}`,`='Resumo por Base'!A${4+i}`,`='Resumo por Base'!E${4+i}`,`='Resumo por Base'!F${4+i}`]];}
dash.getRange('C10:C19').format.numberFormat='0.0%';dash.getRange('D10:D19').format.numberFormat='0.0%';box(dash,'A10:D19');
dash.getRange('F8:H8').merge();dash.getRange('F8').values=[['LEITURA DA REGRA']];dash.getRange('F8').format={font:{bold:true,color:navy,size:12}};
dash.getRange('F9:H13').merge(true);dash.getRange('F9:H13').values=[['1. DS por rota precisa ser ≥ 92%.'],['2. Ambulâncias: Cluster = ROTA.'],['3. Reserva FF: preencher cadastro próprio.'],['4. Utilização oficial depende da frota planejada.'],['* Bônus abaixo é uma simulação por participação FF.']];dash.getRange('F9:H13').format={font:{color:muted,size:10},wrapText:true};box(dash,'F9:H13',pale);
dash.getRange('A22:H22').merge();dash.getRange('A22').values=[['IMPORTANTE: a planilha não possui frota FF planejada/disponível; por isso a coluna “Participação FF” é um proxy, não a utilização oficial da regra.']];dash.getRange('A22').format={fill:'#FFF4E5',font:{color:'#9A6A2E',bold:true,size:10},wrapText:true};dash.getRange('A22').format.rowHeight=28;
dash.getRange('J4:K14').values=[['Base','Participação FF'],...summary.slice(0,10).map(x=>[x.base,null])];for(let i=5;i<=14;i++)dash.getRange(`K${i}`).formulas=[[`='Resumo por Base'!E${i-1}`]];dash.getRange('K5:K14').format.numberFormat='0.0%';
const chart=dash.charts.add('bar',dash.getRange('J4:K14'));chart.title='Top 10 bases · participação FF';chart.hasLegend=false;chart.setPosition('F15','H31');chart.yAxis={numberFormatCode:'0%'};
dash.getRange('A1:H31').format.font={name:'Aptos'};dash.getRange('A:A').format.columnWidth=18;dash.getRange('B:B').format.columnWidth=28;dash.getRange('C:D').format.columnWidth=18;dash.getRange('E:F').format.columnWidth=18;dash.getRange('G:H').format.columnWidth=20;dash.freezePanes.freezeRows(4);

setTitle(base,'A1:H1','RESUMO POR BASE · JULHO 2026','Cálculos derivados a partir das 26.435 linhas da aba Geral');
base.getRange('A3:H3').values=[['Base','Rotas FF totais','Rotas FF','Ambulâncias excluídas','Participação FF*','DS médio FF','Bônus proxy*','Status']];hdr(base,'A3:H3');
const baseRows=summary.map((x,i)=>[x.base,x.total,x.ff,x.ambulance,null,null,null,null]);base.getRange(`A4:H${3+baseRows.length}`).values=baseRows;
for(let i=4;i<4+baseRows.length;i++){base.getRange(`E${i}:H${i}`).formulas=[[`=IFERROR(C${i}/B${i},0)`,`=IFERROR(SUMIF('Rotas FF'!$A$4:$A$797,A${i},'Rotas FF'!$D$4:$D$797)/COUNTIF('Rotas FF'!$A$4:$A$797,A${i}),0)`,`=IF(F${i}<92%,0,IF(E${i}>=100%,1000,IF(E${i}>=95%,700,IF(E${i}>=90%,350,0))))`,`=IF(F${i}<92%,\"DS abaixo de 92%\",IF(E${i}>=100%,\"Faixa 100%\",IF(E${i}>=95%,\"Faixa 95%\",IF(E${i}>=90%,\"Faixa 90%\",\"Abaixo de 90%\"))))`]];}
base.getRange(`E4:F${3+baseRows.length}`).format.numberFormat='0.0%';base.getRange(`G4:G${3+baseRows.length}`).format.numberFormat='R$ #,##0';base.getRange(`A3:H${3+baseRows.length}`).format.font={name:'Aptos',size:10};base.getRange('A3:H3').format.rowHeight=24;base.getRange(`A4:H${3+baseRows.length}`).format.borders={insideHorizontal:{style:'thin',color:'#EEEEF2'}};base.getRange(`A4:H${3+baseRows.length}`).conditionalFormats.add('cellIs',{operator:'greaterThanOrEqual',formula:'92%',format:{fill:'#E3F8EF',font:{color:'#208A60',bold:true}}});base.getRange('A:A').format.columnWidth=31;base.getRange('B:D').format.columnWidth=16;base.getRange('E:G').format.columnWidth=19;base.getRange('H:H').format.columnWidth=22;base.tables.add(`A3:H${3+baseRows.length}`,true,'ResumoBaseTable');base.freezePanes.freezeRows(3);

setTitle(routes,'A1:J1','ROTAS FF ELEGÍVEIS · JULHO 2026','Fonte filtrada da aba Geral · classificação do veículo contém “FROTA FIXA” · Cluster = ROTA removido');
routes.getRange('A3:J3').values=[['Base','Data','Placa','DS%','Rota Logistics','Cluster','Veículo','Contrato','Ambulância?','Observação']];hdr(routes,'A3:J3');
const serialToDate=(serial)=>new Date(Date.UTC(1899,11,30)+Number(serial)*86400000);
const routeRows=ffRoutes.map(r=>[r.base,serialToDate(r.data_serial),r.placa,r.ds/100,r.rota,(r.cluster ? `'${r.cluster}` : ''),r.veiculo,r.contrato,'Não',r.observacao]);routes.getRange(`A4:J${3+routeRows.length}`).values=routeRows;routes.getRange(`B4:B${3+routeRows.length}`).format.numberFormat='dd/mm/yyyy';routes.getRange(`D4:D${3+routeRows.length}`).format.numberFormat='0.0%';routes.getRange(`A3:J${3+routeRows.length}`).format.font={name:'Aptos',size:9};routes.getRange('A:A').format.columnWidth=30;routes.getRange('B:B').format.columnWidth=13;routes.getRange('C:C').format.columnWidth=12;routes.getRange('D:D').format.columnWidth=10;routes.getRange('E:F').format.columnWidth=16;routes.getRange('G:H').format.columnWidth=30;routes.getRange('I:I').format.columnWidth=14;routes.getRange('J:J').format.columnWidth=55;routes.tables.add(`A3:J${3+routeRows.length}`,true,'RotasFFTable');routes.freezePanes.freezeRows(3);

setTitle(rules,'A1:E1','REGRAS DE BONIFICAÇÃO · FROTA FIXA','Parâmetros fornecidos pelo solicitante');rules.getRange('A3:E8').values=[['Critério','Faixa','Valor','Aplicação','Fonte'],['DS por rota','≥ 92%','—','Portão obrigatório','Imagem anexada'],['Utilização FF','> 100%','R$ 1.300','Após portão DS','Regra vigente'],['Utilização FF','100%','R$ 1.000','Após portão DS','Imagem anexada'],['Utilização FF','95%','R$ 700','Após portão DS','Imagem anexada'],['Utilização FF','90%','R$ 350','Após portão DS','Imagem anexada']];hdr(rules,'A3:E3');rules.getRange('A3:E8').format.borders={insideHorizontal:{style:'thin',color:'#EEEEF2'}};rules.getRange('A:A').format.columnWidth=22;rules.getRange('B:B').format.columnWidth=16;rules.getRange('C:C').format.columnWidth=16;rules.getRange('D:D').format.columnWidth=25;rules.getRange('E:E').format.columnWidth=18;rules.getRange('A10:E13').values=[['Ponto pendente','Impacto','Como resolver','Status','Observação'],['Reserva FF','Não existe coluna explícita no arquivo','Usar a aba Cadastro Reserva FF com placa, vigência e ativo','Estruturado','Só entra após cadastro'],['Frota planejada','Não permite calcular utilização oficial','Enviar quantidade/dias disponíveis por base','Pendente','Proxy usado: rotas FF / rotas totais'],['Ambulância','Identificada pela coluna Cluster = ROTA','Exclusão automática por Cluster','Aplicado','Não usar Observação como fonte principal']];hdr(rules,'A10:E10');rules.getRange('A10:E13').format.borders={insideHorizontal:{style:'thin',color:'#EEEEF2'}};rules.getRange('A10:E13').format.wrapText=true;rules.getRange('A:A').format.columnWidth=22;rules.getRange('B:B').format.columnWidth=35;rules.getRange('C:C').format.columnWidth=42;rules.getRange('D:D').format.columnWidth=15;rules.getRange('E:E').format.columnWidth=35;

setTitle(dict,'A1:C1','DICIONÁRIO DE DADOS','Mapeamento usado na leitura do arquivo original');dict.getRange('A3:C11').values=[['Campo do modelo','Coluna origem','Uso'],['Base','Geral!A','Agrupamento da análise'],['Data','Geral!B','Período da rota'],['DS%','Geral!AB','DS por rota'],['Cluster','Geral!K','Ambulância quando valor = ROTA'],['Classificação do veículo','Geral!AI','Identificação de Frota Fixa'],['Veículo Portal','Geral!H','Conferência da classificação'],['Observação','Geral!AH','Contexto; não é fonte principal de ambulância'],['Tipo de Contrato','Geral!F','Contexto operacional']];hdr(dict,'A3:C3');dict.getRange('A3:C11').format.borders={insideHorizontal:{style:'thin',color:'#EEEEF2'}};dict.getRange('A:A').format.columnWidth=28;dict.getRange('B:B').format.columnWidth=22;dict.getRange('C:C').format.columnWidth=45;dict.getRange('A1:C11').format.wrapText=true;

setTitle(reserve,'A1:G1','CADASTRO RESERVA FF','Preencher para que uma rota de reserva seja reconhecida de forma auditável');reserve.getRange('A3:G3').values=[['Base','Placa','Identificador veículo','Vigência inicial','Vigência final','Ativa?','Observação']];hdr(reserve,'A3:G3');reserve.getRange(`A4:A${3+summary.length}`).values=summary.map(x=>[x.base]);reserve.getRange(`B4:G${3+summary.length}`).values=summary.map(()=>['','','','','Não','']);reserve.getRange(`D4:E${3+summary.length}`).format.numberFormat='dd/mm/yyyy';reserve.getRange(`F4:F${3+summary.length}`).dataValidation={rule:{type:'list',values:['Sim','Não']}};reserve.getRange(`A3:G${3+summary.length}`).format.borders={insideHorizontal:{style:'thin',color:'#EEEEF2'}};reserve.getRange('A:A').format.columnWidth=31;reserve.getRange('B:C').format.columnWidth=22;reserve.getRange('D:E').format.columnWidth=17;reserve.getRange('F:F').format.columnWidth=12;reserve.getRange('G:G').format.columnWidth=40;reserve.getRange(`A3:G${3+summary.length}`).format.wrapText=true;reserve.freezePanes.freezeRows(3);

const preview=await wb.render({sheetName:'Dashboard FF',range:'A1:H31',scale:1.5,format:'png'});await fs.writeFile(`${outDir}/dashboard_ff_preview.png`,new Uint8Array(await preview.arrayBuffer()));
for (const [sheetName, range] of [['Resumo por Base','A1:H20'],['Rotas FF','A1:J20'],['Regras','A1:E13'],['Dicionário','A1:C11'],['Cadastro Reserva FF','A1:G20']]) { const img=await wb.render({sheetName,range,scale:1,format:'png'}); await fs.writeFile(`${outDir}/${sheetName.replace(/[^a-z0-9]/gi,'_')}_preview.png`,new Uint8Array(await img.arrayBuffer())); }
const check=await wb.inspect({kind:'table',sheetId:'Dashboard FF',range:'A1:H22',include:'values,formulas',tableMaxRows:25,tableMaxCols:10,maxChars:12000});console.log(check.ndjson);
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:100},summary:'formula error scan'});console.log(errors.ndjson);
const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save(`${outDir}/bonificacao_ff_julho_2026.xlsx`);
